name: Linting, Testing, Building
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    Pipleine:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x]
        steps:
            - uses: actions/checkout@v2
            - name: Staring Node.js ${{matrix.node-version}}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{matrix.node-version}}
            - name: install modules
              run: npm install --f
            - name: build production project
              run: npm run build:prod
              if: always()
            - name: linter for typescript
              run: npm run lint:ts
              if: always()
            - name: linter for scss
              run: npm run lint:scss
              if: always()
            - name: unit testing
              run: npm run test:unit
